spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/sprintplanner
    username: dev
    password: 123
  jpa:
    properties.hibernate:
      show_sql: true
      ddl-auto: none
      hbm2ddl.auto: none
  flyway:
    url: jdbc:postgresql://localhost:5400/sprintplanner
    schemas: public
    user: "dev"
    password: "123"

server.error:
  include-exception: true
  include-stacktrace: always

logging:
  pattern.console: "%d{HH:mm:ss.SSS} %clr(%4p) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
