## --------------------------------------------------
## | TODO: Add production properties here |
## --------------------------------------------------

spring:
  jpa:
    hibernate:
      ddl-auto: none