CREATE TABLE TICKETS (ID INT PRIMARY KEY, TICKET_NAME VARCHAR(255), CREATOR VARCHAR(255));
INSERT INTO TICKETS (ID, TICKET_NAME, CREATOR) VALUES (1, 'bootstrap cpsc 304 project', 'nick');
CREATE TABLE USERS (ID UUID PRIMARY KEY, USERNAME VARCHAR(255) UNIQUE, PASSWORD VARCHAR(255));
